package Modelos;
// Generated 24/02/2018 01:40:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Jugadores generated by hbm2java
 */
public class Jugadores  implements java.io.Serializable {


     private int id;
     private String apodo;
     private Set participacionesUno = new HashSet(0);
     private Set participacionesDos = new HashSet(0);
     private Set participaciones = new HashSet(0);

    public Jugadores() {
    }

	
    public Jugadores(int id, String apodo) {
        this.id = id;
        this.apodo = apodo;
    }
    public Jugadores(int id, String apodo, Set participacionesDos, Set participacionesUno) {
       this.id = id;
       this.apodo = apodo;
       this.participacionesUno = participacionesUno;
       this.participacionesDos = participacionesDos;
       this.participaciones = participacionesUno;
       this.participaciones.addAll(participacionesDos);
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getApodo() {
        return this.apodo;
    }
    
    public void setApodo(String apodo) {
        this.apodo = apodo;
    }
    public Set getParticipacionesUno() {
        return this.participacionesUno;
    }
    
    public void setParticipacionesUno(Set participacionesUno) {
        this.participacionesUno = participacionesUno;
    }
    public Set getParticipacionesDos() {
        return this.participacionesDos;
    }
    
    public void setParticipacionesDos(Set participacionesDos) {
        this.participacionesDos = participacionesDos;
    }
    
    public Set getParticipaciones() {
        return this.participaciones;
    }
    public void setParticipaciones(Set participaciones) {
        this.participaciones = participaciones;
    }

}


