package Modelos;
// Generated 24/02/2018 01:40:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partidas generated by hbm2java
 */
public class Partidas  implements java.io.Serializable {


     private int id;
     private Date fecha;
     private int puntajeMax;
     private Set participantes = new HashSet(0);

    public Partidas() {
    }

	
    public Partidas(int id, Date fecha, int puntajeMax) {
        this.id = id;
        this.fecha = fecha;
        this.puntajeMax = puntajeMax;
    }
    public Partidas(int id, Date fecha, int puntajeMax, Set participantes) {
       this.id = id;
       this.fecha = fecha;
       this.puntajeMax = puntajeMax;
       this.participantes = participantes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getPuntajeMax() {
        return this.puntajeMax;
    }
    
    public void setPuntajeMax(int puntajeMax) {
        this.puntajeMax = puntajeMax;
    }
    public Set getParticipantes() {
        return this.participantes;
    }
    
    public void setParticipantes(Set participantes) {
        this.participantes = participantes;
    }
}


