package Modelos;
// Generated 25/02/2018 01:34:48 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Participantes generated by hbm2java
 */
public class Participantes  implements java.io.Serializable {


     private int id;
     private Jugadores jugadoresByJugadorDosId;
     private Jugadores jugadoresByJugadorUnoId;
     private Partidas partidas;
     private String nombreGrupo;
     private int puntaje;
     private Set rondases = new HashSet(0);

    public Participantes() {
    }

	
    public Participantes(Jugadores jugadoresByJugadorUnoId, Partidas partida) {
        this.jugadoresByJugadorUnoId = jugadoresByJugadorUnoId;
        this.partidas = partida;
        this.partidas.getParticipanteses().add(this);
        this.jugadoresByJugadorUnoId.getParticipantesesForJugadorUnoId().add(this);
    }
    public Participantes(Jugadores jugadoresByJugadorUnoId, Jugadores jugadoresByJugadorDosId, Partidas partida) {
       this.jugadoresByJugadorDosId = jugadoresByJugadorDosId;
       this.jugadoresByJugadorUnoId = jugadoresByJugadorUnoId;
       this.partidas = partida;
       this.partidas.getParticipanteses().add(this);
       this.jugadoresByJugadorUnoId.getParticipantesesForJugadorUnoId().add(this);
       this.jugadoresByJugadorDosId.getParticipantesesForJugadorDosId().add(this);
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Jugadores getJugadoresByJugadorDosId() {
        return this.jugadoresByJugadorDosId;
    }
    
    public void setJugadoresByJugadorDosId(Jugadores jugadoresByJugadorDosId) {
        this.jugadoresByJugadorDosId = jugadoresByJugadorDosId;
    }
    public Jugadores getJugadoresByJugadorUnoId() {
        return this.jugadoresByJugadorUnoId;
    }
    
    public void setJugadoresByJugadorUnoId(Jugadores jugadoresByJugadorUnoId) {
        this.jugadoresByJugadorUnoId = jugadoresByJugadorUnoId;
    }
    public Partidas getPartidas() {
        return this.partidas;
    }
    
    public void setPartidas(Partidas partidas) {
        this.partidas = partidas;
    }
    public String getNombreGrupo() {
        return this.nombreGrupo;
    }
    
    public void setNombreGrupo(String nombreGrupo) {
        this.nombreGrupo = nombreGrupo;
    }
    public int getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(int puntaje) {
        this.puntaje = puntaje;
    }
    public Set getRondases() {
        return this.rondases;
    }
    
    public void setRondases(Set rondases) {
        this.rondases = rondases;
    }

    public void sumPuntaje(int punt) {
        this.puntaje += punt;
    }

}


