package Modelos;
// Generated 24/02/2018 01:40:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Participantes generated by hbm2java
 */
public class Participantes  implements java.io.Serializable {


     private ParticipantesId id;
     private Jugadores jugadorDos;
     private Jugadores jugadorUno;
     private Partidas partida;
     private String nombreGrupo;
     private Set rondas = new HashSet(0);

    public Participantes() {
    }

	
    public Participantes(ParticipantesId id, Jugadores jugadorUno, Partidas partida) {
        this.id = id;
        this.jugadorUno = jugadorUno;
        this.partida = partida;
    }
    public Participantes(ParticipantesId id, Jugadores jugadorDos, Jugadores jugadorUno, Partidas partida, String nombreGrupo, Set rondas) {
       this.id = id;
       this.jugadorDos = jugadorDos;
       this.jugadorUno = jugadorUno;
       this.partida = partida;
       this.nombreGrupo = nombreGrupo;
       this.rondas = rondas;
    }
   
    public ParticipantesId getId() {
        return this.id;
    }
    
    public void setId(ParticipantesId id) {
        this.id = id;
    }
    public Jugadores getJugadorDos() {
        return this.jugadorDos;
    }
    
    public void setJugadorDos(Jugadores jugadorDos) {
        this.jugadorDos = jugadorDos;
    }
    public Jugadores getJugadorUno() {
        return this.jugadorUno;
    }
    
    public void setJugadorUno(Jugadores jugadorUno) {
        this.jugadorUno = jugadorUno;
    }
    public Partidas getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partidas partida) {
        this.partida = partida;
    }
    public String getNombreGrupo() {
        return this.nombreGrupo;
    }
    
    public void setNombreGrupo(String nombreGrupo) {
        this.nombreGrupo = nombreGrupo;
    }
    public Set getRondas() {
        return this.rondas;
    }
    
    public void setRondas(Set rondas) {
        this.rondas = rondas;
    }




}


